"""Added Verifier Table

Revision ID: 87979bc177ff
Revises: 03666958086e
Create Date: 2023-01-14 19:34:33.024170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87979bc177ff'
down_revision = '03666958086e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verifier')
    # ### end Alembic commands ###
